### ISSUE TITLE
Technical TODO list

### ISSUE THREAD

**Issue by ggiorgino3** [ggiorgino3/dreamtheatercms#7]
- [x] Code-style definition with pre-commit scripts
- [x] - dockerization
- [x] #9
- [x] #10 
- [x] - Auth service provider
- [ ] #8
- [x] - CI / CD w\ GH actions
